[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.13.1"
  NPM_FLAGS = "--prefer-offline --no-audit"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
